In [16]:
# Import Pandas as Alias
# Syntax for Importing (Import Library_Name as Alias_Name)
import pandas as pd

# **Load Dataset**

In [5]:
# Read Data from google Drive
data = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Python/cleaned_data.xlsx")

# Reading first 5 rows using Head Function

In [6]:
data.head()

,Transaction_ID,Purchase_Date,Customer_Type,Product_Category,Quantity,Unit_Price,Revenue,City
0,MISSING-281,2026-01-23,New,Groceries,5,17.73,132.12,Garowe
1,MISSING-47,2026-03-10,Returning,Electronics,2,168.49,88.65,Bosaso
2,MISSING-125,2025-01-05,Returning,Home & Living,3,131.14,336.98,Kismayo
3,MISSING-150,2025-06-21,Returning,Electronics,1,228.02,393.42,Kismayo
4,MISSING-151,2025-07-09,Returning,Stationery,6,12.28,228.02,Baidoa

# Read the last 5 Rows

In [7]:
data.tail()

,Transaction_ID,Purchase_Date,Customer_Type,Product_Category,Quantity,Unit_Price,Revenue,City
286,TRX00223,2099-12-31,Returning,Electronics,6,263.68,2416.12,Mogadishu
287,TRX00292,2026-07-22,New,Electronics,7,180.56,1582.08,Hargeisa
288,TRX00289,2025-11-08,Returning,Groceries,7,14.78,1263.92,Mogadishu
289,TRX00290,2025-11-12,Returning,Clothing,1,25.90,103.46,Garowe
290,TRX00291,2025-04-29,New,Other,2,21.57,25.90,Baidoa

# Using Sample

In [8]:
data.sample()

,Transaction_ID,Purchase_Date,Customer_Type,Product_Category,Quantity,Unit_Price,Revenue,City
26,TRX00020,2025-10-04,New,Groceries,1,12.01,721.14,Mogadishu

In [ ]:
data.sample(10)

,Transaction_ID,Purchase_Date,Customer_Type,Product_Category,Quantity,Unit_Price,City
131,TRX00148,2026-02-09,Returning,Groceries,6,18.27,Baidoa
110,TRX00278,2025-01-21,New,Groceries,6,28.43,Mogadishu
83,TRX00105,2025-02-09,Returning,Electronics,2,206.18,Hargeisa
125,TRX00217,2025-11-12,Returning,Home & Living,5,95.46,Mogadishu
256,TRX00072,2025-10-07,Returning,Home & Living,5,113.84,Hargeisa
233,TRX00157,2025-04-09,New,Electronics,2,340.00,Kismayo
68,TRX00234,2025-02-18,Returning,Clothing,6,34.22,Garowe
264,TRX00239,2026-04-19,Returning,Home & Living,5,93.44,Hargeisa
136,TRX00009,2026-07-09,New,Clothing,8,45.98,Bosaso
76,TRX00225,2025-04-07,Returning,Stationery,5,6.36,Kismayo

In [9]:
data.shape

(291, 8)

In [ ]:
data.columns

Index(['Transaction_ID', 'Purchase_Date', 'Customer_Type', 'Product_Category',
       'Quantity', 'Unit_Price', 'City'],
      dtype='object')

In [17]:
data.dtypes

Transaction_ID              object
Purchase_Date       datetime64[ns]
Customer_Type               object
Product_Category            object
Quantity                     int64
Unit_Price                 float64
Revenue                    float64
City                        object
dtype: object

# General summary of Data

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 291 entries, 0 to 290
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    291 non-null    object
 1   Purchase_Date     291 non-null    datetime64[ns]
 2   Customer_Type     291 non-null    object
 3   Product_Category  291 non-null    object
 4   Quantity          291 non-null    int64
 5   Unit_Price        291 non-null    float64
 6   Revenue           291 non-null    float64
 7   City              291 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 18.3+ KB

## Display the describe of statistics using Describe Function

In [12]:
data.describe(include="all")

,Transaction_ID,Purchase_Date,Customer_Type,Product_Category,Quantity,Unit_Price,Revenue,City
count,291,291,291,291,291.000000,291.000000,291.000000,291
unique,291,NaN,2,6,NaN,NaN,NaN,7
top,TRX00291,NaN,Returning,Groceries,NaN,NaN,NaN,Mogadishu
freq,1,NaN,158,77,NaN,NaN,NaN,113
mean,NaN,2029-08-04 06:50:43.298969088,NaN,NaN,4.422680,152.654399,682.108729,NaN
min,NaN,2025-01-01 00:00:00,NaN,NaN,1.000000,4.930000,5.180000,NaN
25%,NaN,2025-05-28 12:00:00,NaN,NaN,2.000000,19.940000,64.610000,NaN
50%,NaN,2025-10-16 00:00:00,NaN,NaN,4.000000,52.560000,185.550000,NaN
75%,NaN,2026-03-10 00:00:00,NaN,NaN,6.000000,155.270000,499.070000,NaN
max,NaN,2099-12-31 00:00:00,NaN,NaN,31.000000,2013.000000,10882.550000,NaN
std,NaN,NaN,NaN,NaN,3.236116,268.722909,1474.193098,NaN

In [15]:
data.sample(frac=1)

,Transaction_ID,Purchase_Date,Customer_Type,Product_Category,Quantity,Unit_Price,Revenue,City
245,TRX00257,2025-03-09,Returning,Electronics,1,225.04,78.24,Mogadishu
267,TRX00278,2025-01-21,New,Groceries,6,28.43,182.27,Mogadishu
50,TRX00047,2025-04-02,Returning,Electronics,2,266.16,196.62,Mogadishu
69,TRX00058,2099-12-31,Returning,Electronics,5,235.34,41.95,Mogadishu
176,TRX00188,2025-06-26,Returning,Electronics,1,319.92,999.16,Mogadishu
...,...,...,...,...,...,...,...,...
65,TRX00053,2026-03-10,Returning,Other,2,64.44,84.08,Bosaso
11,MISSING-79,2025-02-02,Returning,Electronics,8,210.00,193.44,Mogadishu
250,TRX00262,2025-12-29,Returning,Clothing,8,39.08,205.92,Hargeisa
166,TRX00135,2026-07-04,Returning,Groceries,8,1008.97,65.10,Bosaso
167,TRX00179,2025-07-23,New,Clothing,6,42.20,8071.76,Mogadishu